#!/bin/bash
if [[ $# -ne 2 ]]
then
	echo "$0 <name> <namespace>"
	exit 1
fi
NAME=$1
NS=$2

if ! [[ $NAME =~ ^[a-zA-Z]([0-9a-zA-Z]){1,15}$ ]]
then
	echo "$NAME is wrong"
	exit 1
fi

if ! [[ $NS =~ ^[0-9a-f]+$ ]]
then
	echo "namespace is wrong"
	exit 1
fi
if [[ ! -d ~/.vm/namespace/$NS ]]
then
	echo "NO NAMESPACE"
	exit 12
fi
[[ ! -d ~/.vm/namespace/$NS/vm ]] && mkdir ~/.vm/namespace/$NS/vm 
if [[ -L ~/.vm/namespace/$NS/vm/$NAME ]]
then
	(
		flock -w 5 -x 10 || exit 19
		/usr/bin/lxc delete $NAME --force
	       	RC=$?
		if [[ $RC -eq 0 ]]	
		then
			source ~/.vm/pool/$NAME
                	sudo /var/www/system/bin/tstop $NAME 
			/var/www/scripts/free_port $LXD_PORT
			rm ~/.vm/namespace/$NS/vm/$NAME
			rm ~/.vm/pool/$NAME
		else
			echo "XXX"
			exit 23
		fi
	
	) 10>~/.vm/.lock
else
	echo "VM IS NOT AVAILIBLE"
	exit 10
fi
