#!/bin/bash
if [[ $# -ne 1 ]]
then
	echo "$0 <name>"
	exit 1
fi
NAME=$1

if ! [[ $NAME =~ ^[a-zA-Z]([0-9a-zA-Z]){1,15}$ ]]
then
	echo "$NAME is wrong"
	exit 1
fi
pass=$(/usr/bin/pwgen -B 10 1)

if [[ ! -f ~/.vm/pool/$NAME ]]
then
	(
		flock -w 5 -x 10 || exit 19
		/usr/bin/lxc launch --profile ubuntu ubuntu-devops $NAME -c security.nesting=true 2>&1
		[[ $? -ne 0 ]] && exit 15
		echo "ubuntu:$pass" | /usr/bin/lxc exec $NAME chpasswd 
		echo "LXD_PASS=$pass" >~/.vm/pool/$NAME.tmp
		tport=$(/var/www/scripts/find_port $NAME)
		echo "LXD_USER=ubuntu" >>~/.vm/pool/$NAME.tmp
		echo "LXD_NAME=$NAME" >>~/.vm/pool/$NAME.tmp
		echo "LXD_PORT=$tport" >>~/.vm/pool/$NAME.tmp
		/usr/bin/lxc stop $NAME
		mv ~/.vm/pool/$NAME.tmp ~/.vm/pool/$NAME
		ln -s ~/.vm/pool/$NAME ~/.vm/free/$NAME
		flock -u 10
	) 10>~/.vm/.lock
else
	exit 10
fi

