#!/bin/bash
exit 233
if [[ $# -ne 1 ]]
then
	echo "$0 <name>"
	exit 1
fi
NAME=$1

if ! [[ $NAME =~ ^[a-zA-Z]([0-9a-zA-Z]){1,15}$ ]]
then
	echo "$NAME is wrong"
	exit 1
fi
pass=$(/usr/bin/pwgen -B 8 1)

if [[ ! -f ~/.vm/pool/$NAME ]]
then
	(
		flock -n 10 || exit 1
		/usr/bin/lxc launch --profile ubuntu ubuntu-devops $NAME 2>&1
		[[ $? -ne 0 ]] && exit 15
		echo "ubuntu:$pass" | /usr/bin/lxc exec $NAME chpasswd 
		echo "LXD_PASS=$pass" >~/.vm/pool/$NAME.tmp
		mv ~/.vm/pool/$NAME.tmp ~/.vm/pool/$NAME
		ln -s ~/.vm/pool/$NAME ~/.vm/free/$NAME
		
	) 10>>~/.vm/.lock
else
	exit 10
fi

