#!/bin/bash
if [[ $# -ne 2 ]]
then
	echo "$0 <name> <namespace>"
	exit 1
fi
NAME=$1
NS=$2

if ! [[ $NAME =~ ^[a-zA-Z]([0-9a-zA-Z]){1,15}$ ]]
then
	echo "$NAME is wrong"
	exit 1
fi

if ! [[ $NS =~ ^[0-9a-f]+$ ]]
then
	echo "namespace is wrong"
	exit 1
fi
if [[ ! -d ~/.vm/namespace/$NS ]]
then
	echo "NO NAMESPACE"
	exit 12
fi
[[ ! -d ~/.vm/namespace/$NS/vm ]] && mkdir ~/.vm/namespace/$NS/vm 
if [[ -L ~/.vm/namespace/$NS/vm/$NAME ]]
then
	(
		flock -w 5 -x 10 || exit 19
                sudo /var/www/system/bin/tstop $NAME 
		/usr/bin/lxc stop $NAME
	
	) 10>~/.vm/.lock
else
	echo "VM IS NOT AVAILIBLE"
	exit 10
fi
